### ISSUE TITLE
Introduction to Rake

### ISSUE THREAD

**Issue by lashd** [sky-uk/ruby-bootcamp#10]
After candidates have completed the ruby quiz they are going to need to know how to create some of the standard infrastructure around the projects.

An exercise or Rake would be good vehicle to also get them to wire up running tests a code coverage.

**Comment by lashd** [comment]
Thinking that this might be a good [video](https://www.youtube.com/watch?v=AFPWDzHWjEY) to watch:

**Comment by joshnesbitt** [comment]
Yeah that looks good.

**Comment by lashd** [comment]
I'm thinking that the exercises you be two fold for this one:
1. An exercise write a Rakefile using third party tasks for some code that is supplied
2. The exercise that @joshnesbitt has been working on that get's participants to write and test their own tasks.

**Comment by joshnesbitt** [comment]
Sounds good to me. I'm looking at integrating my repo into this one tomorrow morning, i'll do it in a PR so not to confuse candidates.

**Comment by lashd** [comment]
cool

**Comment by lashd** [comment]
@joshnesbitt is it ok if I grab your code for the rake exercise now and put in to what I am building?

**Comment by joshnesbitt** [comment]
@lashd absolutely.

**Comment by lashd** [comment]
@joshnesbitt thanks, in the exercise you have written, you give an example file listing output. Do you have those files? I could check them in as test data for them to play with?

**Comment by joshnesbitt** [comment]
They're just stock images, sure thing:

http://wearest.ac/17h6U

You'll want to change the glob pattern to `*.jpg` for these.

**Comment by lashd** [comment]
@joshnesbitt Thanks, I'll mix in a couple of text files for variety and update the description

**Comment by joshnesbitt** [comment]
@lashd great cheers. Let me know if you want a review.

**Comment by lashd** [comment]
Nearly there

**Comment by lashd** [comment]
I'm thinking that candidates should wire in third party rake tasks for the first part of this exercise.

The two I am thinking of are:
- RSpec
- Rubocop

With regards to rubocop they could use the autocorrect feature to fix the easy ones and then configure rubocop:
- change maximum line length
- disable module comment check in a particular spec file

@joshnesbitt what do you think

**Comment by joshnesbitt** [comment]
@lashd sounds good. Got an example of how you'd like to see third party tasks included?

**Comment by lashd** [comment]
I was thinking just in the way that the projects themselves document it. This way they are also compelled to go off and read the docs for a couple of projects.
e.g.

```
require 'rubocop/rake_task'

RuboCop::RakeTask.new
```

These implementations also will demonstrate a testable way of implementing portable tasks?

**Comment by joshnesbitt** [comment]
Yeah that would be good, maybe even link to the task source so they can have a dig around.

**Comment by joshnesbitt** [comment]
Just had a look through this, looks great. Not sure you need the "Thirdparty Tasks" heading though?

**Comment by lashd** [comment]
This has been merged, so let's close this one down and see how people get on with it.
