### ISSUE TITLE
RSpec Material

### ISSUE THREAD

**Issue by lashd** [sky-uk/ruby-bootcamp#11]
Material on RSpec is pretty thin on the ground at the moment. 

We need to:
- Identify a final set of materials for candidates to watch/read. These would be added to the Prezi etc...
- Identify which exercises we can also use to introduce some of the different RSpec fundamentals.

**Comment by lashd** [comment]
Some of the finer aspects of RSpec are being introduced along side other topics. For example, [Exercise 8](https://github.com/Ladtech/ruby-bootcamp/tree/master/exercise-8) covers shared examples whilst going through mixins.

What other areas should we be going through?

E.g.
- shared_context/include_context
- metadata
- hooks #I'm inclined to think that people should already have knowledge of hooks as they are prevalent in pretty much any test framework.

**Comment by lashd** [comment]
Contemplating asking candidates to copy the source from exercise 7 in to lib of this exercise and test drive a new class as well as providing tests for those that were copied in.

**Comment by joshnesbitt** [comment]
I think hooks should be covered very briefly, just in case. Meta data is important when you get into larger suites, so I'd maybe cover that briefly after hooks. Then as you said a good `shared_context` example would be great.

> Contemplating asking candidates to copy the source from exercise 7 in to lib of this exercise and test drive a new class as well as providing tests for those that were copied in.

Agree this would work. Maybe add in a suite for it then extend the functionality slightly?

**Comment by lashd** [comment]
@joshnesbitt and I have just been speaking and we think that the "Rock, paper  scissors' game shown in the video.

**Comment by joshnesbitt** [comment]
I think we cover this well enough now across quite a few exercises.
