### ISSUE TITLE
Sinatra Content

### ISSUE THREAD

**Issue by lashd** [sky-uk/ruby-bootcamp#31]

**Comment by lashd** [comment]
I have already written an exercise (14) for Sinatra. But am on the look out for content:

http://code.tutsplus.com/tutorials/singing-with-sinatra--net-18965

**Comment by lashd** [comment]
Maybe it is worth writing a seperate prezi on this one as it is a major topic... pulling out Sinatra's major features.

**Comment by joshnesbitt** [comment]
Yeah a separate prezi might be a good shout as it's the core tech used upstairs?

**Comment by lashd** [comment]
I've put a [prezi](http://prezi.com/mlsa1jwsn-o0/?utm_campaign=share&utm_medium=copy&rc=ex0share) together for Sinatra and have hooked it up to the main dashboard

**Comment by joshnesbitt** [comment]
Sorry just seen this, looked at it a week ago, looks good!
